remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Bardhyl Miftari]
description: [Phd Student in computer engineering and optimization at the University of Liège - Belgium. Contact: [here](https://www.uliege.be/cms/c_9054334/fr/repertoire?uid=u235534)]
logo: profile.jpg
